/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bonus: typeof import('./src/components/Bonus.vue')['default']
    CarbonBadge: typeof import('~icons/carbon/badge')['default']
    CarbonCircleSolid: typeof import('~icons/carbon/circle-solid')['default']
    CarbonGift: typeof import('~icons/carbon/gift')['default']
    CarbonGift2: typeof import('~icons/carbon/gift2')['default']
    CarbonInfo: typeof import('~icons/carbon/info')['default']
    CarbonInformation: typeof import('~icons/carbon/information')['default']
    CarbonLink: typeof import('~icons/carbon/link')['default']
    CarbonReset: typeof import('~icons/carbon/reset')['default']
    CarbonSave: typeof import('~icons/carbon/save')['default']
    Field: typeof import('./src/components/game/Field.vue')['default']
    Index: typeof import('./src/components/game/Index.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    InfoBlock: typeof import('./src/components/modal/InfoBlock.vue')['default']
    Item: typeof import('./src/components/status/Item.vue')['default']
    Letter: typeof import('./src/components/letters/Letter.vue')['default']
    MdiCheck: typeof import('~icons/mdi/check')['default']
    MdiClose: typeof import('~icons/mdi/close')['default']
    Panel: typeof import('./src/components/status/Panel.vue')['default']
    Prize: typeof import('./src/components/modal/Prize.vue')['default']
    PrizeBlock: typeof import('./src/components/modal/PrizeBlock.vue')['default']
    Row: typeof import('./src/components/game/Row.vue')['default']
    WordsEnded: typeof import('./src/components/modal/WordsEnded.vue')['default']
  }
}
